// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example for specifying per-platform Firebase options:
/// ```dart
/// switch (defaultTargetPlatform) {
///   case TargetPlatform.android:
///     return android;
///   case TargetPlatform.iOS:
///     return ios;
///   case TargetPlatform.macOS:
///     return macos;
///   case TargetPlatform.windows:
///     return windows;
///   case TargetPlatform.linux:
///     return linux;
///   default:
///     return web;
/// }
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtlxcc7CkT0pjS1-o8q0KLo8UYP7N8efo',
    appId: '1:27412997936:web:2841eca3529993c762caf5',
    messagingSenderId: '27412997936',
    projectId: 'cocina-en-tu-casa',
    authDomain: 'cocina-en-tu-casa.firebaseapp.com',
    storageBucket: 'cocina-en-tu-casa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeqJ5tAUzsbLs6cJ2VDb3f82H8hfUDuDY',
    appId: '1:27412997936:android:e4b1fd9085175a3962caf5',
    messagingSenderId: '27412997936',
    projectId: 'cocina-en-tu-casa',
    storageBucket: 'cocina-en-tu-casa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT2EIzbXwPKc7SqegtxDtWQXG2JfXQIck',
    appId: '1:27412997936:ios:82aba1ebb76011e762caf5',
    messagingSenderId: '27412997936',
    projectId: 'cocina-en-tu-casa',
    storageBucket: 'cocina-en-tu-casa.firebasestorage.app',
    iosBundleId: 'com.example.myFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT2EIzbXwPKc7SqegtxDtWQXG2JfXQIck',
    appId: '1:27412997936:ios:82aba1ebb76011e762caf5',
    messagingSenderId: '27412997936',
    projectId: 'cocina-en-tu-casa',
    storageBucket: 'cocina-en-tu-casa.firebasestorage.app',
    iosBundleId: 'com.example.myFirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtlxcc7CkT0pjS1-o8q0KLo8UYP7N8efo',
    appId: '1:27412997936:web:49ff004dae86180d62caf5',
    messagingSenderId: '27412997936',
    projectId: 'cocina-en-tu-casa',
    authDomain: 'cocina-en-tu-casa.firebaseapp.com',
    storageBucket: 'cocina-en-tu-casa.firebasestorage.app',
  );

}